version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: postgres
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: '2gb'
  web: &app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - node-data:/app/node_modules:cached
      - /app/.git
    environment:
      HOME: /app
      RAILS_ENV: development
      # @see https://github.com/titusfortner/webdrivers/issues/148#issuecomment-538507857
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
      - "3035:3035"
    tty: true
    depends_on:
      - db

volumes:
  bundle:
    driver: local
  data:
    driver: local
  node-data:
    driver: local
